site_name: Yaoyaolingbro's computer learning notebook
site_url: https://yaoyaolingbro.github.io/notebook
site_author: yaoyaoling

repo_url: https://github.com/Yaoyaolingbro/Notebook
repo_name: Yaoyaolingbro/Notebook


theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.prune
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    #　- navigation.expand
    - navigation.tracking
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - meta # 支持markdown博客文件头的元数据，比如标题
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - admonition  # 支持提示块
  - pymdownx.details  # 提示块可折叠
  - attr_list 
  - pymdownx.inlinehilite # 支持行内语法高亮
  # - pymdownx.highlight: # 支持代码块语法高亮，！！！跟mermaid冲突
  #     linenums: true # 显示行号
  - pymdownx.superfences: # 可在列表等处嵌入块
      # make exceptions to highlighting of code:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid

plugins:
  - search:
      lang: zh
  # - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Yaoyaolingbro/notebook/home
  analytics:
    provider: google
    property: G-KJB4RXSKZG


nav:
  - Home: index.md
  - ZJU_CS:
    - ZJU_CS/index.md
    - HPC: 
      - ZJU_CS/HPC/index.md
      - ZJU_CS/HPC/AIPP.md
      - Note: 
        - ZJU_CS/HPC/class/index.md
        - ZJU_CS/HPC/class/L1.md
        - ZJU_CS/HPC/class/L2.md
        - ZJU_CS/HPC/class/L3.md
        - ZJU_CS/HPC/class/L4.md
        - ZJU_CS/HPC/class/L5.md
        - ZJU_CS/HPC/class/L6.md
        - ZJU_CS/HPC/class/L7.md
        - ZJU_CS/HPC/class/L8.md
      - Lab: 
        - ZJU_CS/HPC/homework/lab1.md
        - ZJU_CS/HPC/homework/lab2.md
        - ZJU_CS/HPC/homework/lab2.5.md
        - ZJU_CS/HPC/homework/lab3.md
        - ZJU_CS/HPC/homework/lab4.md
        - ZJU_CS/HPC/homework/lab5.md
    - FDS:
      - ZJU_CS\FDS\index.md
      - ZJU_CS\FDS\algorithm.md
      - ZJU_CS\FDS\graph.md
      - ZJU_CS\FDS\hash.md
      - ZJU_CS\FDS\heap.md
      - ZJU_CS\FDS\set.md
      - ZJU_CS\FDS\sort.md
      - ZJU_CS\FDS\tree.md
      - ZJU_CS\FDS\homework.md
    - Big data security and privacy protection:
      - ZJU_CS\Big data security and privacy protection\index.md
      - ZJU_CS\Big data security and privacy protection\cryptographic.md
      - ZJU_CS\Big data security and privacy protection\homework\homework1.md
      - ZJU_CS\Big data security and privacy protection\homework\homework2.md
      - ZJU_CS\Big data security and privacy protection\homework\homework3.md
      - ZJU_CS\Big data security and privacy protection\homework\project.md
    - Digital desin:
      - ZJU_CS\DigitalDesign\index.md
      - ZJU_CS\DigitalDesign\Chap01.md
      - ZJU_CS\DigitalDesign\Chap02.md
      - ZJU_CS\DigitalDesign\Chap03.md
      - ZJU_CS\DigitalDesign\Chap04.md
      - ZJU_CS\DigitalDesign\Chap05.md
      - ZJU_CS\DigitalDesign\Chap06.md
      - ZJU_CS\DigitalDesign\Chap07.md
      - ZJU_CS\DigitalDesign\glossary.md

  - Missing semester: 
    - Missing semester/index.md
    - Missing semester/toolbox.md
    - Git: 
      - Missing semester/Git/index.md
      - Missing semester/Git/fast_git.md
      - Missing semester/Git/note.md
    - Markdown: 
      - Missing semester/Markdown/index.md
    - Linux: 
      - Missing semester/Linux/index.md
      - Missing semester/Linux/shell.md
      - Missing semester/Linux/C.md
      - Missing semester/Linux/WSL.md
      - Missing semester/Linux/advanced Linux.md
      - Missing semester/Linux/vim.md
    - Docker:
      - Missing semester/Docker/index.md
    - Ladder:
      - Missing semester/Ladder/index.md
    - Latex:
      - Missing semester/Latex/index.md
    - Mkdocs material:
      - Missing semester/Mkdocs material/index.md

  - Online CS Courses:
    - 计算机科学导论: 
      - Online CS Courses/Fundation of computer science/index.md
    - CSAPP: 
      - Online CS Courses/CSAPP/index.md
      - Online CS Courses/CSAPP/note.md
    - CS106L: 
      - Online CS Courses/CS106L/index.md
      - Online CS Courses/CS106L/Lecture1.md
    - CS50 AI:
      - Online CS Courses/CS50 AI/index.md
      - Online CS Courses/CS50 AI/note.md
    - CS61B:
      - Online CS Courses\CS61B\index.md
      - Online CS Courses\CS61B\note.md
    - CS106X:
      - Online CS Courses\CS106X\index.md

  - AI:
    - AI入门:
      - AI/AI入门/index.md
    - 机器学习:
      - AI/机器学习/index.md
      - AI/机器学习/introduction.md
    - 深度学习:
      - AI/深度学习/index.md
    - Pytorch:
      - AI\Pytorch\index.md
  
  - Language:
    - C:
      - Language\Advanced C Language\index.md
    - Python:
      - Language\Python\index.md
    - Verilog:
      - Language\Verilog\index.md
    - C++:
      - Language\C++\index.md
  
  - Scientific research:
    - Scientific research\index.md

  - Spark in life:
    - College life:
      - spark in life\college life\competition.md
      - spark in life\college life\freshman.md
      - spark in life\college life\second year.md
    - Skill:
      - spark in life\skills\cook.md
      - spark in life\skills\driver license.md
      - spark in life\skills\kickboxing.md
      - spark in life\skills\virtual location.md
    - Travel:
      - spark in life\travel\GuiZhou.md