site_name: Yaoyaoling's notebook
site_url: https://yaoyaolingbro.github.io/notebook
site_author: yaoyaoling

repo_url: https://github.com/Yaoyaolingbro/Notebook
repo_name: Yaoyaolingbro/Notebook


theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.prune
    # - navigation.instant
    - navigation.tracking
    - navigation.indexes
    #　- navigation.expand
    - navigation.tracking
    - navigation.top
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    - material.extensions.emoji.twemoji
    
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

  
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.superfences: # 可在列表等处嵌入块
      # make exceptions to highlighting of code:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - meta # 支持markdown博客文件头的元数据，比如标题
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - attr_list 
  - pymdownx.highlight: # 支持代码块语法高亮，！！！跟mermaid冲突
  # - linenums: true # 显示行号

plugins:
  - changelog
  - search:
      lang: zh
  - mermaid2
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - css/custom.css
  - css/card.css
  - css/tasklist.css
  - css/flink.css
  - css/more_changelog.css
  

extra_javascript:
  - js/baidu-tongji.js
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Yaoyaolingbro/notebook/home
  analytics:
    provider: google
    property: G-KJB4RXSKZG


nav:
  - Home: index.md
  - ZJU_CS:
    - ZJU_CS/index.md
    - HPC: 
      - ZJU_CS/HPC/index.md
      - ZJU_CS/HPC/AIPP.md
      - Note: 
        - ZJU_CS/HPC/class/index.md
        - ZJU_CS/HPC/class/L1.md
        - ZJU_CS/HPC/class/L2.md
        - ZJU_CS/HPC/class/L3.md
        - ZJU_CS/HPC/class/L4.md
        - ZJU_CS/HPC/class/L5.md
        - ZJU_CS/HPC/class/L6.md
        - ZJU_CS/HPC/class/L7.md
        - ZJU_CS/HPC/class/L8.md
      - Lab: 
        - ZJU_CS/HPC/homework/lab1.md
        - ZJU_CS/HPC/homework/lab2.md
        - ZJU_CS/HPC/homework/lab2.5.md
        - ZJU_CS/HPC/homework/lab3.md
        - ZJU_CS/HPC/homework/lab4.md
        - ZJU_CS/HPC/homework/lab5.md
    - FDS:
      - ZJU_CS/FDS/index.md
      - ZJU_CS/FDS/algorithm.md
      - ZJU_CS/FDS/graph.md
      - ZJU_CS/FDS/hash.md
      - ZJU_CS/FDS/heap.md
      - ZJU_CS/FDS/set.md
      - ZJU_CS/FDS/sort.md
      - ZJU_CS/FDS/tree.md
      - ZJU_CS/FDS/homework.md
      - ZJU_CS/FDS/exam.md
    - Digital desin:
      - ZJU_CS/DigitalDesign/index.md
      - ZJU_CS/DigitalDesign/Chap01.md
      - ZJU_CS/DigitalDesign/Chap02.md
      - ZJU_CS/DigitalDesign/Chap03.md
      - ZJU_CS/DigitalDesign/Chap04.md
      - ZJU_CS/DigitalDesign/Chap05.md
      - ZJU_CS/DigitalDesign/Chap06.md
      - ZJU_CS/DigitalDesign/Chap07.md
      - ZJU_CS/DigitalDesign/glossary.md
      - ZJU_CS/DigitalDesign/exam.md
      - ZJU_CS/DigitalDesign/learnskill.md
    - Discrete math:
      - ZJU_CS/Discrete math/index.md
      - ZJU_CS/Discrete math/note.md
      - ZJU_CS/Discrete math/exam.md
    - OOP:
      - ZJU_CS/oop/index.md
      - ZJU_CS/oop/mid-review.md
      - ZJU_CS/oop/final-review.md
    - ADS:
      - ZJU_CS/ADS/index.md
      - ZJU_CS/ADS/homework.md
      - ZJU_CS/ADS/week1.md
      - ZJU_CS/ADS/week2.md
      - ZJU_CS/ADS/week3.md
      - ZJU_CS/ADS/week4.md
      - ZJU_CS/ADS/week5.md
      - ZJU_CS/ADS/week6.md
      - ZJU_CS/ADS/week7.md
      - ZJU_CS/ADS/week8.md
      - ZJU_CS/ADS/week9.md
      - ZJU_CS/ADS/week10.md
      - ZJU_CS/ADS/week11.md
      - ZJU_CS/ADS/week12.md
      - ZJU_CS/ADS/week13.md
      - ZJU_CS/ADS/week14.md
      - ZJU_CS/ADS/week15.md
    - Database:
      - ZJU_CS/Database/index.md
      - ZJU_CS/Database/review.md
      - ZJU_CS/Database/week1.md
      - ZJU_CS/Database/week2.md
      - ZJU_CS/Database/week3.md
      - ZJU_CS/Database/week4.md
      - ZJU_CS/Database/week5.md

    - Computer Organazation:
      - ZJU_CS/computer_organization/index.md
      - ZJU_CS/computer_organization/1_prelude.md
      - ZJU_CS/computer_organization/2_instructions.md
      - ZJU_CS/computer_organization/3_arithmetic.md
      - ZJU_CS/computer_organization/4_processor.md
      - ZJU_CS/computer_organization/5_cache.md
      - ZJU_CS/computer_organization/6_IO.md
      - ZJU_CS/computer_organization/历年卷.md

  - Missing semester: 
    - Missing semester/index.md
    - Missing semester/toolbox.md
    - Missing semester/copilot.md
    - Git: 
      - Missing semester/git/index.md
      - Missing semester/git/fastGit.md
      - Missing semester/git/note.md
    - Markdown: 
      - Missing semester/Markdown/index.md
    - Linux: 
      - Missing semester/Linux/index.md
      - Missing semester/Linux/shell.md
      - Missing semester/Linux/C.md
      - Missing semester/Linux/WSL.md
      - Missing semester/Linux/advanced Linux.md
      - Missing semester/Linux/vim.md
      - Missing semester/Linux/tmux.md
    - Docker:
      - Missing semester/Docker/index.md
    - Ladder:
      - Missing semester/Ladder/index.md
    - Latex:
      - Missing semester/Latex/index.md
    - Mkdocs material:
      - Missing semester/Mkdocs material/index.md
    - Zotero:
      - Missing semester/Zotero/index.md
      - Missing semester/Zotero/use.md

  - Online CS Courses:
    - 计算机科学导论: 
      - Online CS Courses/Fundation of computer science/index.md
    - CSAPP: 
      - Online CS Courses/CSAPP/index.md
      - Online CS Courses/CSAPP/note.md
    - CS106L: 
      - Online CS Courses/CS106L/index.md
      - Online CS Courses/CS106L/note.md
    - CS50 AI:
      - Online CS Courses/CS50 AI/index.md
      - Online CS Courses/CS50 AI/note.md
    - CS61B:
      - Online CS Courses/CS61B/index.md
      - Online CS Courses/CS61B/note.md
    - CS106X:
      - Online CS Courses/CS106X/index.md

  - AI:
    - AI/index.md
    - AI/DL.md
    - Machine Learning:
      - AI/machine learning/index.md
      - AI/machine learning/introduction.md
      - AI/machine learning/method.md
    - Pytorch:
      - AI/Pytorch/index.md
      - AI/Pytorch/note.md
  
  - Language:
    - C:
      - Language/Advanced C Language/index.md
    - C++:
      - Language/C++/index.md
      - Language/C++/stl.md
      - Language/C++/experience.md
    - CUDA:
      - Language/CUDA/index.md
      - Language/CUDA/note.md
      - Language/CUDA/GEMM.md
      - Language/CUDA/cutlass.md
    - Python:
      - Language/Python/index.md
      - Language/Python/fastpython.md
      - Language/Python/skill.md
      - Language/Python/enviroment.md
    - Verilog:
      - Language/Verilog/index.md

  - English:
    - English/index.md
    - research:
      - English/research/index.md
      - English/research/note.md
    - IELTS words:
      - English/IELTS words/index.md
      - English/IELTS words/chapter1.md
    
  
  - Scientific research:
    - Scientific research/index.md
    - Scientific research/writing.md
    - Scientific research/ode.md
    - 4science:
      - Scientific research/4science/index.md
      - Scientific research/4science/protein_hierachy.md
    - mathematic model:
      - Scientific research/mathematic model/index.md
      - Scientific research/mathematic model/mcm.md
    - Basic tutor:
      - Scientific research/basic tutor/voice synthesis.md
    - Zhaozhou:
      - Scientific research/Zz/index.md
      - 23 NIPS:
        - Scientific research/Zz/23NIPS/index.md
        - Scientific research/Zz/23NIPS/note.md

  - Paper Reading:
    - Paper Reading/index.md
    - Basic Model:
      - Paper Reading/basic model/index.md
      - Paper Reading/basic model/transformer.md
      - Paper Reading/basic model/cnn.md
      - Paper Reading/basic model/rnn.md

    - Protein:
      - Paper Reading/protein/index.md

  - Spark in life:
    - spark in life/index.md
    - College life:
      - spark in life/college life/competition.md
      - spark in life/college life/freshman.md
    - Skill:
      - spark in life/skills/cook.md
      - spark in life/skills/driver license.md
      - spark in life/skills/kickboxing.md
      - spark in life/skills/virtual location.md
    - Travel:
      - spark in life/travel/GuiZhou.md
      - spark in life/travel/chongqing.md